Second homework
alexander-kurdakov/semprojecthm2020 pull request #2
Opened 2020-09-24 22:34 UTC by alexander-kurdakov

6 заданий с тестами.
в некоторых из них есть "защита от дурака"

2020-09-25 06:36 UTC, gsvgit requested changes

2020-09-25 06:36 UTC, gsvgit commented on README.md
> ----
А как во вторую домашку попали изменения из первой?

2020-09-25 06:36 UTC, gsvgit commented on src/homework/Main.fs
> +            if size<1 then
Бинарные операции лучше выделять пробелами с двух сторон
```size < 1```

2020-09-25 06:36 UTC, gsvgit commented on src/homework/Main.fs
> +            printf"enter range (to): "
Аргументы от функции тоже лучше пробелами отделять.

2020-09-25 06:36 UTC, gsvgit commented on src/homework/Main.fs
> +            let array=[|first;second|]
Лучше каждое решение выделить в функцию

2020-09-25 06:36 UTC, gsvgit commented on src/homework/hw2.fs
> +
Лишние переводы строк.

2020-09-25 06:36 UTC, gsvgit commented on src/homework/hw2.fs
> +
А зачем дублировать здесь и в  main?

2020-09-25 06:36 UTC, gsvgit commented on src/homework/hw2.fs
> +
Правда ли, что индексы всегда в "хорошем" диапазоне?

2020-09-25 06:36 UTC, gsvgit commented on tests/homework.Tests/Tests.fs
> +            let test=homework.hw2.first_ex 0
А не в нуле правильно считается? А что будет, если в диапазон ничего не попало? Нужно больше тестов.

2020-09-26 13:04 UTC, alexander-kurdakov commented on README.md
> ----
я почему то решил создать эту ветку от локального мастера, а там README.md был не обновлен

2020-09-26 13:44 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            if size<1 then
исправлено

2020-09-26 13:44 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            printf"enter range (to): "
исправлено

2020-09-26 13:47 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +
исправлено

2020-09-26 13:49 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +
у меня было две функции, для мейна и для тестов..... исправил

2020-09-26 14:39 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            let array=[|first;second|]
исправлено

2020-09-28 15:51 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +
теперь плохие индексы будет опознавать сама функция

2020-09-28 15:51 UTC, alexander-kurdakov commented on tests/homework.Tests/Tests.fs
> +            let test=homework.hw2.first_ex 0
сделал рандомные тесты

2020-09-30 10:05 UTC, gsvgit requested changes

2020-09-30 10:05 UTC, gsvgit commented on tests/homework.Tests/Tests.fs
> +            let test=homework.hw2.secondEx  0
И снова пробелы.

2020-09-30 10:05 UTC, gsvgit commented on README.md
> ----
И, судя по всему, сейчас получите конфликт при слиянии веток. Удачи)

2020-09-30 10:05 UTC, gsvgit commented on src/homework/Main.fs
> +        | Third_exercise
Мы уже говорили о том, что подчёрки в именах в .NET не приняты.

2020-09-30 10:05 UTC, gsvgit commented on src/homework/Main.fs
> +                                printf "%A " out.[i]
Откуда стролько пробелов?

2020-09-30 10:05 UTC, gsvgit commented on src/homework/Main.fs
> +            let size = Console.ReadLine()|>int
То есть пробелы, то их нету. Должны быть

2020-09-30 10:05 UTC, gsvgit commented on src/homework/Main.fs
> +                    then
А почему то есть перенос на новую строку, то нет? Вообще, можно блок из одной строки писать на той же строке, что и  ```then``` Просто унифицируйте.

2020-09-30 10:05 UTC, gsvgit commented on src/homework/Main.fs
> +            printf"enter range (to): "
Что-то строка всё ещё приклеена к функции печати.

2020-09-30 10:05 UTC, gsvgit commented on src/homework/Main.fs
> +            if out = [|6;6;6|]
Круто. А что если такой массив на вход сгенерируется?

2020-09-30 10:05 UTC, gsvgit commented on src/homework/hw2.fs
> +        then
И снова странные переносы: то есть, то нет

2020-09-30 10:05 UTC, gsvgit commented on tests/homework.Tests/Tests.fs
> +            let test=homework.hw2.firstEx  1
И снова отсутствуют пробелы.

2020-09-30 12:51 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +                                printf "%A " out.[i]
исправлено, какая-то аномалия

2020-09-30 13:04 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +    let  secondEx x =
исправлено

2020-09-30 13:05 UTC, alexander-kurdakov commented on tests/homework.Tests/Tests.fs
> +            let test=homework.hw2.secondEx  0
исправлено

2020-09-30 13:17 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +        then
теперь, если после then одно выражение, то оно пишется сразу после него, иначе после ентера

2020-09-30 13:17 UTC, alexander-kurdakov commented on tests/homework.Tests/Tests.fs
> +            let test=homework.hw2.firstEx  1
исправлено

2020-09-30 13:28 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            let size = Console.ReadLine()|>int
поправил

2020-09-30 13:29 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            let size = Console.ReadLine()|>int
исправил

2020-09-30 13:30 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +                    then
теперь, если после then одно выражение, то оно пишется сразу после него, иначе после ентера

2020-09-30 13:40 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +                    then
теперь, если после then одно выражение, то оно пишется сразу после него, иначе после ентера

2020-09-30 13:41 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +                                printf "%A " out.[i]
исправил.

2020-09-30 13:41 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            printf"enter range (to): "
исправил

2020-09-30 15:54 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +        | First_exercise
исправил

2020-09-30 16:04 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            if out = [|6;6;6|]
да, я забыл что здесь не массив индексов возвращается... исправил

2020-09-30 16:05 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +        | Third_exercise
исправлено

2020-09-30 17:09 UTC, gsvgit requested changes
Подумайте аккуратнее над обработкой исключительных ситуаций.

2020-09-30 17:09 UTC, gsvgit commented on src/homework/hw2.fs
> +                let errorArray = Array.zeroCreate (array.Length + 1)
Я специально в Телеге писал о том, как обрабатывать исключительные ситуации.

2020-09-30 21:13 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +                let errorArray = Array.zeroCreate (array.Length + 1)
извиняюсь, почему-то подумал, что это не касается этой домашки.

2020-10-02 07:06 UTC, gsvgit approved these changes
Ок. А замечания учтите в следующих домашках. Ну и это была далеко не третья попытка.

2020-10-02 07:06 UTC, gsvgit commented on src/homework/hw2.fs
> +    let firstEx x =  x * x * x * x + x * x * x + x * x + x + (1) |> int
А зачем скобки вокруг единицы?

2020-10-02 07:06 UTC, gsvgit commented on src/homework/hw2.fs
> +    let fifthEx first second =
А вот пустые строки между функциями на верхнем уровне не помешали бы. Чтобы всё в одно полотно не слипалось.

2020-10-02 19:46 UTC, merged