Third Homework
alexander-kurdakov/semprojecthm2020 pull request #3
Opened 2020-10-15 11:02 UTC by alexander-kurdakov

third homework with tests

2020-10-15 11:05 UTC, alexander-kurdakov commented
конфликты пофикшу, не понимаю почему они возникают .....

2020-10-16 06:46 UTC, gsvgit requested changes
1) Я просил не сливать кучу домашек в один реквест. У Вас тут много чего из пердыдущих посему-то.
2) Конфликты. Их быть не должно. Судя по всему, если Вы разберётесь с первым пунктом, то и конфликты решатся.

2020-10-16 06:46 UTC, gsvgit commented on src/homework/hw2.fs
> +    let firstEx x =  x * x * x * x + x * x * x + x * x + x + (1) |> int
Я просил не сливать кучу домашек в олин реквест.

2020-10-16 15:11 UTC, alexander-kurdakov commented on src/homework/hw2.fs
> +    let firstEx x =  x * x * x * x + x * x * x + x * x + x + (1) |> int
да, мне пришлось вернуться к комиту, который был совершен еще до сдачи 2 домашки, не проконтролировал, видимо

2020-10-16 20:19 UTC, closed without merging