Third homework
alexander-kurdakov/semprojecthm2020 pull request #4
Opened 2020-10-18 13:57 UTC by alexander-kurdakov

Исправил все проблемы. Третье домашнее задание.

2020-10-22 08:18 UTC, gsvgit requested changes
С матрицами хорошо всё оформили, здорово. Немного надо улучшить оформление кода (elif и прочее форматирование). Ну и ещё пара замечаний в коментариях.

2020-10-22 08:18 UTC, gsvgit commented on src/homework/hw3.fs
> +        else if n = 0 || n = 1 then n
если так, то есть elif. Ну и мешать then на одной строке с if, а else уже на следующей --- не очень хорошая затея.

2020-10-22 08:18 UTC, gsvgit commented on tests/homework.Tests/Main.fs
> +let config = { FsCheckConfig.defaultConfig with maxTest = 5 }
А что так мало?)

2020-10-22 08:18 UTC, gsvgit commented on tests/homework.Tests/TestsForThirdHW.fs
> +            if abs n > 30
сдаётся мне, можно написать короче:
```
let n' = abs <| if abs n > 30 then n % 10 else n
Expect.equal (homework.hw3.fifthExercise n')  (homework.hw3.fourthExercise n')
```

2020-10-22 19:38 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +        else if n = 0 || n = 1 then n
т.е. вместо else if лучше писать elif?

2020-10-22 19:56 UTC, gsvgit commented
Да.
Regards,
Semyon Grigorev.


чт, 22 окт. 2020 г. в 22:38, Alexander Kurdakov <notifications@github.com>:

> *@alexander-kurdakov* commented on this pull request.
> ------------------------------
>
> In src/homework/hw3.fs
> <https://github.com/alexander-kurdakov/semprojecthm2020/pull/4#discussion_r510410225>
> :
>
> > @@ -0,0 +1,54 @@
>
> +namespace homework
>
> +
>
> +module hw3 =
>
> +    let rec fibRec n =
>
> +        if n < 0 then failwith ("wrong index of fibnumber")
>
> +        else if n = 0 || n = 1 then n
>
>
> т.е. вместо else if лучше писать elif?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexander-kurdakov/semprojecthm2020/pull/4#discussion_r510410225>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQAOEHNDCEZOQT7L2FLSMCC5BANCNFSM4SVDGTRA>
> .
>

2020-10-25 10:51 UTC, gsvgit requested changes

2020-10-25 10:51 UTC, gsvgit commented on src/homework/hw3.fs
> +            let out = homework.matrixes.powMatrixnaively m1 (n - 1)
А что кейсом  Naively не выделили?

2020-10-25 10:51 UTC, gsvgit commented on src/homework/matrixes.fs
> +        let n = m1.[0].Length
Вот это можно было бы вынести перед ```if```-ом и использовать тогда и в нём. Тогда сам if опрятнее бы выглядел.

2020-10-25 10:51 UTC, gsvgit commented on src/homework/matrixes.fs
> +            multiplyMartix (optimizedPow m1 (pow / 2) ) (optimizedPow m1 (pow / 2) )
Такая себе оптимизация. ```optimizedPow m1 (pow / 2)``` Вы всё равно два раза считаете.

2020-10-25 10:51 UTC, gsvgit commented on tests/homework.Tests/TestsForThirdHW.fs
> +        testProperty "is equal  naive to optimized?" <| fun (n:int) ->
Остальные реализации тоже можно бы проверить.

2020-10-25 10:51 UTC, gsvgit commented on tests/homework.Tests/TestsForThirdHW.fs
> +            Expect.equal (homework.hw3.fifthExercise (alt)) (homework.hw3.fourthExercise (alt)) "fib naive not equal to optimized"
А зачам altв скобках? И что означает это название?

2020-10-25 10:51 UTC, gsvgit commented on src/homework/hw3.fs
> +           let array = Array.zeroCreate (n+1)
Пробелы.

2020-10-25 13:18 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +           let array = Array.zeroCreate (n+1)
ok.

2020-10-25 13:20 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +            let out = homework.matrixes.powMatrixnaively m1 (n - 1)
ok.

2020-10-25 13:55 UTC, alexander-kurdakov commented on tests/homework.Tests/TestsForThirdHW.fs
> +        testProperty "is equal  naive to optimized?" <| fun (n:int) ->
ок.

2020-10-25 13:58 UTC, alexander-kurdakov commented on tests/homework.Tests/TestsForThirdHW.fs
> +            Expect.equal (homework.hw3.fifthExercise (alt)) (homework.hw3.fourthExercise (alt)) "fib naive not equal to optimized"
ok.

2020-10-25 14:16 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        let n = m1.[0].Length
ок.

2020-10-25 14:16 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +            multiplyMartix (optimizedPow m1 (pow / 2) ) (optimizedPow m1 (pow / 2) )
да.......

2020-10-25 15:23 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +           let array = Array.zeroCreate (n+1)
кажется все починил)

2020-10-26 07:53 UTC, gsvgit requested changes

2020-10-26 07:53 UTC, gsvgit commented on src/homework/matrixes.fs
> +        else powMatrixNaively (multiplyMartix m1 matrixForFib) (pow - 1)
Что? Откуда в простом произведении матриц вдруг взялась матрица для Фибоначчи? Напишите просто возведение в степень произвольной матрицы.

2020-10-26 07:53 UTC, gsvgit commented on src/homework/matrixes.fs
> +        then identityMatrix m1.Length
Что-то странное здесь написано. Как только определена нулевая степень, дальше произвольная степень индуктивно определяется. Зачем отдельно первую рассматривать? Зачем какое-то сложное выражение для произвольной степени?

2020-10-26 09:42 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        else powMatrixNaively (multiplyMartix m1 matrixForFib) (pow - 1)
упс...

2020-10-26 10:34 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        then identityMatrix m1.Length
если честно, не понял вас. Если в первую степень возводим, то нужно вернусть поданную на вход матрицу.

2020-10-26 12:21 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        else powMatrixNaively (multiplyMartix m1 matrixForFib) (pow - 1)
да, перемудрил

2020-10-26 13:54 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        then identityMatrix m1.Length
все осознал
.

2020-10-31 22:36 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        then identityMatrix m1.Length
здравствуйте

2020-11-02 12:39 UTC, alexander-kurdakov commented on src/homework/matrixes.fs
> +        then identityMatrix m1.Length
проверьте пожалуйста

2020-11-03 06:33 UTC, gsvgit requested changes
В основном из-за имён функций, на самом деле, так как рефакторинг обсуждали уже после реквеста. Но теперь придётся сделать.

2020-11-03 06:33 UTC, gsvgit commented on src/homework/Main.fs
>              let size = Console.ReadLine() |> int
Зарефакторите, пожалуйста, этот код, как на парах обсуждали.

2020-11-03 06:33 UTC, gsvgit commented on src/homework/Main.fs
> +            printf "enter number of fib. number: "
Ну и этот тоже.

2020-11-03 06:33 UTC, gsvgit commented on src/homework/hw3.fs
> +    let fourthExercise n =
И тут придумывание адекватных названий пременным дало сбой.

2020-11-03 06:33 UTC, gsvgit commented on tests/homework.Tests/TestsForThirdHW.fs
> +        testProperty "is equal  rec to optimized?" <| fun (n:int) ->
И этот код не забудьте привести в порадок.

2020-11-03 20:12 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +    let fourthExercise n =
Ok.

2020-11-05 10:22 UTC, alexander-kurdakov commented on src/homework/Main.fs
> +            printf "enter number of fib. number: "
ок

2020-11-05 19:37 UTC, alexander-kurdakov commented on tests/homework.Tests/TestsForThirdHW.fs
> +        testProperty "is equal  rec to optimized?" <| fun (n:int) ->
Ок.

2020-11-06 19:38 UTC, gsvgit requested changes

2020-11-06 19:38 UTC, gsvgit commented on src/homework/hw3.fs
> +    let rec firstExercise n = // rec
Мы специально обсуждали, что надо бы нормальные имена функцям давать, а Вы всё наоборот сделали зачем-то. Странные исправления получились.

2020-11-06 20:25 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +    let rec firstExercise n = // rec
:)

2020-11-07 12:34 UTC, alexander-kurdakov commented on src/homework/hw3.fs
> +    let rec firstExercise n = // rec
готово, проверьте пожалуйста

2020-11-07 16:45 UTC, gsvgit approved these changes
Ок.

2020-11-08 12:01 UTC, merged