Fourth homework
alexander-kurdakov/semprojecthm2020 pull request #5
Opened 2020-11-10 22:56 UTC by alexander-kurdakov

fourth homework is ready, in my opinion

2020-11-12 12:03 UTC, gsvgit requested changes
Попробуйте убрать ненужные укузания типов.

2020-11-12 12:03 UTC, gsvgit commented on src/sortProj/fourthHomework.fs
> +    let outArray path (list: array<int>) =
А давайте привыкать не писать типы там, где в этом нет необходимости.

2020-11-12 16:04 UTC, gsvgit commented
Как-то Вы очень локально типы убрали. Правда ли, например, что в сотрировках важно знать, что мы именно коллекци из интов сортируем?

2020-11-13 00:14 UTC, alexander-kurdakov commented on src/sortProj/fourthHomework.fs
> +    let outArray path (list: array<int>) =
согласен. все исправил

2020-11-13 07:46 UTC, gsvgit requested changes

2020-11-13 07:46 UTC, gsvgit commented on src/sortProj/fourthHomework.fs
> +    let outArray path (array: array<int>) =
Не уверен, что тут нужен тип элемента

2020-11-13 07:46 UTC, gsvgit commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
А кто такой byref и зачем он тут нужен?

2020-11-13 08:41 UTC, alexander-kurdakov commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
передача по ссылке.

2020-11-13 08:44 UTC, alexander-kurdakov commented on src/sortProj/fourthHomework.fs
> +    let outArray path (array: array<int>) =
ок.

2020-11-13 15:19 UTC, gsvgit commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
Отлично, а зачем она здесь?

2020-11-13 16:18 UTC, alexander-kurdakov commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
чтобы лишний раз массив не копировать

2020-11-13 16:33 UTC, gsvgit commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
А Вы уверены, что он копируется?

2020-11-13 18:52 UTC, alexander-kurdakov commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
я почему то был уверен, поэтому не решился даже проверить. не копируется.

2020-11-16 16:38 UTC, alexander-kurdakov commented on src/sortProj/sorts.fs
> +    let swapArr (array: byref<array<_>>) i j =
Семен Вячеславович, проверьте пожалуйста

2020-11-17 06:23 UTC, gsvgit approved these changes
Пойдёт. Попробуйте ещё в функциях распаковки-запаковки с типами поиграться. Мне кажется, они там не везде нужны.

2020-11-17 08:35 UTC, merged