Sixth homework
alexander-kurdakov/semprojecthm2020 pull request #6
Opened 2020-11-23 20:37 UTC by alexander-kurdakov

sixth homework is ready

2020-11-24 06:15 UTC, gsvgit requested changes

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +[<Measure>] type line
Эм. Если и line и row  --- это про горизонтальное разбиение, то что есть вертикальное (столбцы)?

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +let readMyMatrix path =
Ну почему "мою". Просто булеву, видимо.

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +                  if chars.[j] = char "1" then yield Coordinates(i*1<line>, j*1<row>)
А кто такой ```yield```? Что он делает и зачем нужен?

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    for i in 0..myMatrix.nLines - 1 do
Предположим, у меня есть матрица (координаты просто парами обозначил)
```
SparseMatrix (4, 4, [(3, 3); (1, 1); (0, 0)])
```

Кажется, она будет напечатана некорректно.

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    let mutable resList = []
И снова мутабельный лист. Не надо так. ТУт либо рекурсия, либо что-то из стандартных функций, либо как-то совсем иначе надо писать.

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +            then resList <- resList @ [Coordinates(firstMult.i, sndMult.j)]
1) Добавление одного элемента в конец --- слишком дорогая операция.
2) При таком подходе у Вас могут дублироваться записи.

2020-11-24 06:15 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    SparseMatrix(int m1.nRows, int m2.nLines, resList)
А зачем тут конвертация в int?

2020-11-24 08:15 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +                  if chars.[j] = char "1" then yield Coordinates(i*1<line>, j*1<row>)
генератор списков,  [здесь можно писать любой код, и формировать элементы списка с помощью оператора yield.]

2020-11-24 08:17 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +    SparseMatrix(int m1.nRows, int m2.nLines, resList)
сравниваются переменные с разными единицами измерения

2020-11-24 09:09 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +[<Measure>] type line
да. исправил

2020-11-24 09:22 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +                  if chars.[j] = char "1" then yield Coordinates(i*1<line>, j*1<row>)
без yield работает. а  узнал о  нем из книжки, примеров без него не видел, поэтому написал

2020-11-24 09:22 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +let readMyMatrix path =
ок.

2020-11-24 10:36 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    SparseMatrix(int m1.nRows, int m2.nLines, resList)
Сравниваются? Разные единицы измерения? Мне казалось,  и ```m1.nRows``` и  ```m1.nLines``` просто инты и не сравниваются они тут.

2020-11-24 19:59 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +    SparseMatrix(int m1.nRows, int m2.nLines, resList)
я думал вы про 56 строчку.

2020-11-24 20:01 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +    for i in 0..myMatrix.nLines - 1 do
ок.

2020-11-24 20:04 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +    for i in 0..myMatrix.nLines - 1 do
теперь вектор с координатами будет упорядоченным

2020-11-24 20:09 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +    let mutable resList = []
ок.

2020-11-24 20:09 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +            then resList <- resList @ [Coordinates(firstMult.i, sndMult.j)]
2 проблема исправил с помощью List.distinct, который удаляет одинаковые элементы из списка

2020-11-26 07:16 UTC, gsvgit requested changes

2020-11-26 07:16 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    for i in 0..myMatrix.nLines - 1 do
1) И снова мутабельные списки.
2) Не понял, почему вдруг список координат станет упорядоченным? Эта функция просто берёт матрицу (откуда-то) и печатает её. И вроде как сама они ничего не упорядочивает.

2020-11-27 06:42 UTC, gsvgit requested changes

2020-11-27 06:42 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    let str = makeString 0 0 "" (List.sort myMatrix.content)
А как задаётся порядок на структурах? Как определяется, какая из двух структур координат больше?

2020-11-27 06:42 UTC, gsvgit commented on tests/sixthHomework.Tests/sixthTests.fs
> +
И всё же добавьте тесты на то, что матрицы правильно записываются в файл. Ну и что читаются тоже.

2020-11-28 22:46 UTC, alexander-kurdakov commented on src/sixthHomework/myMatrix.fs
> +    let str = makeString 0 0 "" (List.sort myMatrix.content)
переделал.

2020-11-30 08:42 UTC, gsvgit approved these changes

2020-11-30 08:42 UTC, gsvgit commented on src/sixthHomework/myMatrix.fs
> +    let charArr = [|for _ in 1..myMatrix.nLines -> Array.replicate myMatrix.nRows '0'|]
Ээх, а могли бы и сортировку оставить, если бы разобрались, как она работает.

2020-11-30 09:39 UTC, merged