Seventh homework
alexander-kurdakov/semprojecthm2020 pull request #7
Opened 2020-12-12 17:07 UTC by alexander-kurdakov

Seventh homework is ready

2020-12-12 19:17 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +        hidReal (MyList.rev fst) snd
И кстати, если так, как у Вас, то тут тоже, кажется, фолд.

2020-12-12 19:19 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +            let func = (fun x -> x + 1)
Почему бы не просто ```(+) 1```?

2020-12-12 19:20 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +            let func = (fun acc x -> acc + x)
Тоже, кажется, можно упростить запись

2020-12-12 19:20 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +            let str1 = List.fold (fun acc x -> acc + x) "" (List.map (fun x -> string x) (makeList size))
И тут

2020-12-12 19:22 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +            Expect.equal (MyTree.fold (fun acc x -> acc + x) 0 testTree) 15 "fold doesn't work"
Ну, и тут тоже.

2020-12-12 19:23 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +    ]
Не нашёл тестов на iter

2020-12-12 19:23 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +            let func = (fun acc x -> acc + x)
Ну и в фолде лучше бы использовать операцию, которая сразу показывает, что свёртка в правильную сторону работает.

2020-12-12 19:24 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +            if myLst.Length > 1
Выглядит как лишняя проверка.

2020-12-14 07:13 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        if myLst.Length > 1
ок.

2020-12-14 09:44 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        hidReal (MyList.rev fst) snd
переделал совсем

2020-12-14 10:53 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        let rec hidReal (acc: list<'T>) (ost: MyList<'T>) =
так и есть.

2020-12-14 12:20 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        | 1 -> (Last lst.Head)
нет

2020-12-14 13:36 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +            hidReal (Last (List.rev lst).Head) (List.rev lst).Tail
хорошо.

2020-12-14 13:54 UTC, alexander-kurdakov commented on tests/seventhHomework.Tests/Tests.fs
> +            let func = (fun x -> x + 1)
это не интуитивно понятно.

2020-12-14 13:54 UTC, alexander-kurdakov commented on src/seventhHomework/MyTree.fs
> +    (float <| MyTree.fold (fun acc x -> acc + x) 0 tree) / (float <| MyTree.fold (fun acc _ -> acc + 1) 0 tree)
можно и так

2020-12-14 13:56 UTC, alexander-kurdakov commented on tests/seventhHomework.Tests/Tests.fs
> +            let func = (fun acc x -> acc + x)
согласен.

2020-12-14 14:04 UTC, alexander-kurdakov commented on tests/seventhHomework.Tests/Tests.fs
> +            let str1 = List.fold (fun acc x -> acc + x) "" (List.map (fun x -> string x) (makeList size))
исправил

2020-12-14 14:14 UTC, alexander-kurdakov commented on tests/seventhHomework.Tests/Tests.fs
> +            Expect.equal (MyTree.fold (fun acc x -> acc + x) 0 testTree) 15 "fold doesn't work"
ок.

2020-12-14 14:14 UTC, alexander-kurdakov commented on tests/seventhHomework.Tests/Tests.fs
> +    ]
точно!

2020-12-14 18:01 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +            if myLst.Length > 1
вы имеете в виду, что нужно переписать функцию полностью? иначе без проверки не обойтись

2020-12-16 09:59 UTC, gsvgit requested changes

2020-12-16 09:59 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +        if myLst.Length > 1
Но почему проверка всё ещё есть?

2020-12-16 09:59 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +        MyList.fold (fun acc elem -> acc @ [elem]) [] myLst
Что-то не очевидно, почему элемент в конец добавляется? Либо фолд в неправиильном порядке проходит исходный список, либо тут инвертированный на выходе получается.

2020-12-16 09:59 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +    if myLst.Length = 1
Что-то кажется, что можно без проверки. У Вас первый вариант в cicle просто сразу вернёт список, если с правильнойдлины начинать.

2020-12-16 09:59 UTC, gsvgit commented on src/seventhHomework/MyTree.fs
> +     let tuple = MyTree.fold (fun (fst, snd) x -> fst + x, snd + 1) (0, 0) tree
Просто сразу напишите ```let (x,y) = ...``` и тогда не надо будет match ниже пистаь

2020-12-16 09:59 UTC, gsvgit commented on tests/seventhHomework.Tests/Tests.fs
> +            Expect.equal (MyList.fold func 0 myLst) (List.fold func 0 lst ) "fold doesn't work"
Делать fold с 0 для тестов --- это сильно. Не надо так.

2020-12-16 11:22 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        if myLst.Length > 1
наверное, Вы не туда посмотрели, я исправил.

2020-12-16 11:30 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +        if myLst.Length > 1
![Screenshot from 2020-12-16 14-28-23](https://user-images.githubusercontent.com/106816/102343096-2ead5100-3fab-11eb-99c3-931d4b83099a.png)
Ну вот у меня на 26 строке всё ещё проверка про которую я говорю, что она избыточна

2020-12-17 12:43 UTC, alexander-kurdakov reviewed
не могу вам ответить =(

2020-12-17 12:43 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        if myLst.Length > 1
у меня почему-то показывает, что ваш комментарий под map, а не rev...

2020-12-17 12:45 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +    if myLst.Length = 1
да, а с неправильной длиной сделает на один проход больше

2020-12-17 12:56 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        MyList.fold (fun acc elem -> acc @ [elem]) [] myLst
фолд же с начала в конец идет, кажется все хорошо, он такой же, как у List

2020-12-21 07:53 UTC, gsvgit approved these changes

2020-12-21 07:53 UTC, gsvgit commented on src/seventhHomework/MyList.fs
> +        MyList.fold (fun acc elem -> acc @ [elem]) [] myLst
:) Всё верно. Мне, правда, всё ещё интересно, зачем Вы у всех функций тип списка явно прописываете. Кажется, почти везде компилятор должен сам догадаться.

2020-12-21 10:30 UTC, alexander-kurdakov commented on src/seventhHomework/MyList.fs
> +        MyList.fold (fun acc elem -> acc @ [elem]) [] myLst
кажется, в этом месте действительно не обязательно, но в остальных ф-циях без этого никак.

2020-12-21 10:30 UTC, merged